image: gitpod/workspace-full

tasks:
  - name: Start Backend
    command: |
      cd spring-boot-server
      ./mvnw spring-boot:run
  - name: Start Frontend
    command: |
      cd react-client
      npm install
      npm start

ports:
  - port: 8080
    onOpen: open-preview
    description: Spring Boot API
  - port: 3000
    onOpen: open-preview
    description: React App
